### ISSUE TITLE
NavigationDrawerFragment might not be attached to the Activity

### ISSUE THREAD

**Issue by cornedor** [cornedor/mayhem#10]
The NavigationDrawerFragment might not be attatched to the Activity wich can cause a crash.

>java.lang.IllegalStateException: Fragment NavigationDrawerFragment{4206e588} not attached to Activity
>at android.support.v4.app.Fragment.getResources(Fragment.java:603)
>at android.support.v4.app.Fragment.getString(Fragment.java:625)
>at nl.deltionmobiel.rooster.NavigationDrawerFragment$1.onSharedPreferenceChanged(NavigationDrawerFragment.java:111)
>at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
>at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:461)
>at nl.deltionmobiel.rooster.DepartmentFragment$1$1.onItemClick(DepartmentFragment.java:143)
>at android.widget.AdapterView.performItemClick(AdapterView.java:298)
>at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
>at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
>at android.widget.AbsListView$3.run(AbsListView.java:3645)
>at android.os.Handler.handleCallback(Handler.java:733)
>at android.os.Handler.dispatchMessage(Handler.java:95)
>at android.os.Looper.loop(Looper.java:136)
>at android.app.ActivityThread.main(ActivityThread.java:5139)
>at java.lang.reflect.Method.invokeNative(Native Method)
>at java.lang.reflect.Method.invoke(Method.java:515)
>at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
>at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
>at dalvik.system.NativeStart.main(Native Method)

**Comment by cornedor** [comment]
Duplicate of #11
